In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn

In [2]:
df=pd.read_csv('train_.csv')
df

id  label                                              tweet
0          1      0   @user when a father is dysfunctional and is s...
1          2      0  @user @user thanks for #lyft credit i can't us...
2          3      0                                bihday your majesty
3          4      0  #model   i love u take with u all the time in ...
4          5      0             factsguide: society now    #motivation
5          6      0  [2/2] huge fan fare and big talking before the...
6          7      0   @user camping tomorrow @user @user @user @use...
7          8      0  the next school year is the year for exams.ðŸ˜...
8          9      0  we won!!! love the land!!! #allin #cavs #champ...
9         10      0   @user @user welcome here !  i'm   it's so #gr...
10        11      0   ↝ #ireland consumer price index (mom) climb...
11        12      0  we are so selfish. #orlando #standwithorlando ...
12        13      0  i get to see my daddy today!!   #80days #getti...
13        14      1  @user #cnn calls #michigan middle school 'buil...
14        15      1  no comment!  in #australia   #opkillingbay #se...
15        16      0  ouch...junior is angry😐#got7 #junior #yugyo...
16        17      0  i am thankful for having a paner. #thankful #p...
17        18      1                             retweet if you agree! 
18        19      0  its #friday! 😀 smiles all around via ig use...
19        20      0  as we all know, essential oils are not made of...
20        21      0  #euro2016 people blaming ha for conceded goal ...
21        22      0  sad little dude..   #badday #coneofshame #cats...
22        23      0  product of the day: happy man #wine tool  who'...
23        24      1    @user @user lumpy says i am a . prove it lumpy.
24        25      0   @user #tgif   #ff to my #gamedev #indiedev #i...
25        26      0  beautiful sign by vendor 80 for $45.00!! #upsi...
26        27      0   @user all #smiles when #media is   !! 😜ðŸ˜...
27        28      0  we had a great panel on the mediatization of t...
28        29      0        happy father's day @user 💓💓💓💓  
29        30      0  50 people went to nightclub to have a good nig...
...      ...    ...                                                ...
31932  31933      0                               @user thanks gemma  
31933  31934      1  @user judd is a  &amp; #homophobic #freemilo #...
31934  31935      1  lady banned from kentucky mall. @user  #jcpenn...
31935  31936      0  ugh i'm trying to enjoy my happy hour drink &a...
31936  31937      0  want to know how to live a   life? do more thi...
31937  31938      0                                 love island 💔  
31938  31939      0  my fav actor #vijaysethupathi ! my fav actress...
31939  31940      0      whew  ðŸ˜
 it's a productive and   #friday!!!
31940  31941      0                 @user she's finally here! @user   
31941  31942      0  passed first year of uni #yay #love #pass #uni...
31942  31943      0  this week is flying by   #humpday - #wednesday...
31943  31944      0   @user modeling photoshoot this friday yay #mo...
31944  31945      0  you're surrounded by people who love you (even...
31945  31946      0  feel like... 😝🐶😎 #dog #summer #hot #h...
31946  31947      1  @user omfg i'm offended! i'm a  mailbox and i'...
31947  31948      1  @user @user you don't have the balls to hashta...
31948  31949      1   makes you ask yourself, who am i? then am i a...
31949  31950      0  hear one of my new songs! don't go - katie ell...
31950  31951      0   @user you can try to 'tail' us to stop, 'butt...
31951  31952      0  i've just posted a new blog: #secondlife #lone...
31952  31953      0                @user you went too far with @user  
31953  31954      0  good morning #instagram #shower #water #berlin...
31954  31955      0  #holiday   bull up: you will dominate your bul...
31955  31956      0  less than 2 weeks ðŸ˜
🙏🏼🍹😎🎵 @us...
31956  31957      0  off fishing t

# Fillinh null values

In [3]:
df.isnull().sum()

id       0
label    0
tweet    0
dtype: int64

In [4]:
df['label'].value_counts()

0    29720
1     2242
Name: label, dtype: int64

In [5]:
X=df['tweet']
y=df['label']

In [42]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25)
X_test.shape

(7991,)

In [7]:
# Creating Dictionary
from sklearn.feature_extraction.text import CountVectorizer
vect=CountVectorizer()
X_train_dtm=vect.fit_transform(X_train)
X_test_dtm=vect.transform(X_test)


In [8]:
X_train_dtm.shape

(23971, 34472)

In [9]:
from sklearn.naive_bayes import MultinomialNB
MB=MultinomialNB()
MB.fit(X_train_dtm,y_train)
MB.score(X_test_dtm,y_test)

0.9574521336503566

In [10]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression()
LR.fit(X_train_dtm,y_train)
LR.score(X_test_dtm,y_test)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.9603303716681266

In [11]:
from sklearn.neighbors import KNeighborsClassifier
KN=KNeighborsClassifier()
KN.fit(X_train_dtm,y_train)
KN.score(X_test_dtm,y_test)

0.9428106619947441

In [12]:
from sklearn.svm import SVC
svC=SVC()
svC.fit(X_train_dtm,y_train)
svC.score(X_test_dtm,y_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.9317982730571893

In [13]:
from sklearn.tree import DecisionTreeClassifier
DT=DecisionTreeClassifier()
DT.fit(X_train_dtm,y_train)
DT.score(X_test_dtm,y_test)

0.9523213615317232

In [14]:
from sklearn.ensemble import RandomForestClassifier
RB=RandomForestClassifier()
RB.fit(X_train_dtm,y_train)
RB.score(X_test_dtm,y_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


0.9553247403328745

In [15]:
from sklearn.metrics import confusion_matrix
tr=confusion_matrix(y_test,MB.predict(X_test_dtm))
tr

array([[7422,   24],
       [ 316,  229]], dtype=int64)

In [16]:
from sklearn.metrics import confusion_matrix
twr=confusion_matrix(y_test,RB.predict(X_test_dtm))
twr

array([[7425,   21],
       [ 336,  209]], dtype=int64)

In [17]:
from sklearn.metrics import confusion_matrix
tre=confusion_matrix(y_test,DT.predict(X_test_dtm))
tre

array([[7313,  133],
       [ 248,  297]], dtype=int64)

In [18]:
from sklearn.metrics import confusion_matrix
ec=confusion_matrix(y_test,svC.predict(X_test_dtm))
ec

array([[7446,    0],
       [ 545,    0]], dtype=int64)

In [19]:
from sklearn.metrics import confusion_matrix
trm=confusion_matrix(y_test,KN.predict(X_test_dtm))
trm

array([[7441,    5],
       [ 452,   93]], dtype=int64)

In [20]:
from sklearn.metrics import confusion_matrix
trj=confusion_matrix(y_test,LR.predict(X_test_dtm))
trj

array([[7397,   49],
       [ 268,  277]], dtype=int64)

In [21]:
from sklearn.metrics import roc_curve,auc,roc_auc_score
fpr,tpr,threshold=roc_curve(y_test,LR.predict_proba(X_test_dtm)[:,1])
fpr1,tpr1,threshold1=roc_curve(y_test,KN.predict_proba(X_test_dtm)[:,1])
fpr2,tpr2,threshold2=roc_curve(y_test,DT.predict_proba(X_test_dtm)[:,1])
fpr3,tpr3,threshold3=roc_curve(y_test,RB.predict_proba(X_test_dtm)[:,1])
fpr4,tpr4,threshold4=roc_curve(y_test,MB.predict_proba(X_test_dtm)[:,1])
print(fpr,tpr,threshold,fpr1,tpr1,threshold1,fpr2,tpr2,threshold2,fpr3,tpr3,threshold3,fpr4,tpr4,threshold4)

[0.00000000e+00 1.34300295e-04 1.34300295e-04 1.34300295e-04
 1.34300295e-04 1.34300295e-04 1.34300295e-04 1.34300295e-04
 2.68600591e-04 2.68600591e-04 4.02900886e-04 4.02900886e-04
 4.02900886e-04 4.02900886e-04 4.02900886e-04 4.02900886e-04
 4.02900886e-04 5.37201182e-04 5.37201182e-04 5.37201182e-04
 5.37201182e-04 5.37201182e-04 5.37201182e-04 5.37201182e-04
 5.37201182e-04 5.37201182e-04 5.37201182e-04 5.37201182e-04
 8.05801773e-04 8.05801773e-04 8.05801773e-04 8.05801773e-04
 8.05801773e-04 9.40102068e-04 9.40102068e-04 1.07440236e-03
 1.07440236e-03 1.20870266e-03 1.20870266e-03 1.34300295e-03
 1.34300295e-03 1.47730325e-03 1.47730325e-03 1.61160355e-03
 1.61160355e-03 1.74590384e-03 1.74590384e-03 1.88020414e-03
 1.88020414e-03 2.01450443e-03 2.01450443e-03 2.14880473e-03
 2.14880473e-03 2.28310502e-03 2.28310502e-03 2.55170561e-03
 2.55170561e-03 3.08890680e-03 3.08890680e-03 3.22320709e-03
 3.22320709e-03 3.35750739e-03 3.35750739e-03 3.49180768e-03
 3.49180768e-03 3.626107

In [22]:
q1=roc_auc_score(y_test,LR.predict(X_test_dtm))
q2=roc_auc_score(y_test,KN.predict(X_test_dtm))
q3=roc_auc_score(y_test,DT.predict(X_test_dtm))
q4=roc_auc_score(y_test,RB.predict(X_test_dtm))
q5=roc_auc_score(y_test,MB.predict(X_test_dtm))
print(q1,q2,q3,q4,q5)


0.7508380831281866 0.5849853501787796 0.7635460945720502 0.6903329661637182 0.7084801395737382


In [23]:
ns=DT.predict_proba(X_test_dtm)
ns

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [1., 0.]])

In [45]:
from sklearn.preprocessing import binarize
fm=binarize(ns,0.60)
fm

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [1., 0.]])

In [46]:
sn=fm[:,1]
sn

array([0., 0., 0., ..., 0., 1., 0.])

In [47]:
tx=sn.astype(int)

In [48]:
g1=confusion_matrix(y_test,tx)
g1

array([[7026,  400],
       [ 535,   30]], dtype=int64)

In [49]:
from sklearn.preprocessing import binarize
fm=binarize(ns,0.70)
sn=fm[:,1]
tx=sn.astype(int)
g2=confusion_matrix(y_test,tx)
g2

array([[7026,  400],
       [ 535,   30]], dtype=int64)

In [50]:
from sklearn.preprocessing import binarize
fm=binarize(ns,0.80)
sn=fm[:,1]
tx=sn.astype(int)
g3=confusion_matrix(y_test,tx)
g3

array([[7026,  400],
       [ 535,   30]], dtype=int64)

In [51]:
from sklearn.preprocessing import binarize
fm=binarize(ns,0.90)
sn=fm[:,1]
tx=sn.astype(int)
g4=confusion_matrix(y_test,tx)
g4

array([[7026,  400],
       [ 535,   30]], dtype=int64)

In [52]:
df1=pd.read_csv('test.csv')

In [53]:
df1

id                                              tweet
0      31963  #studiolife #aislife #requires #passion #dedic...
1      31964   @user #white #supremacists want everyone to s...
2      31965  safe ways to heal your #acne!!    #altwaystohe...
3      31966  is the hp and the cursed child book up for res...
4      31967    3rd #bihday to my amazing, hilarious #nephew...
5      31968                        choose to be   :) #momtips 
6      31969  something inside me dies 💦💿✨  eyes nes...
7      31970  #finished#tattoo#inked#ink#loveit❤️ #❤ï¸...
8      31971   @user @user @user i will never understand why...
9      31972  #delicious   #food #lovelife #capetown mannaep...
10     31973  1000dayswasted - narcosis infinite ep.. make m...
11     31974  one of the world's greatest spoing events   #l...
12     31975  half way through the website now and #allgoing...
13     31976  good food, good life , #enjoy and   🙌🍕ðŸ...
14     31977  i'll stand behind this #guncontrolplease   #se...
15     31978  i ate,i ate and i ate...😀😊   #jamaisasth...
16     31979   @user got my @user limited edition rain or sh...
17     31980  &amp; #love &amp; #hugs &amp; #kisses too! how...
18     31981  👭🌞💖 #girls   #sun #fave @ london, uni...
19     31982  thought factory: bbc neutrality on right wing ...
20     31983  hey guys tommorow is the last day of my exams ...
21     31984   @user @user  @user  #levyrroni #recuerdos mem...
22     31985  my mind is like 🎉💃🏽🏀 but my body l...
23     31986  never been this down on myself in my entire li...
24     31987  check  twitterww - trends: "trending worldwide...
25     31988  i thought i saw a mermaid!!! #ceegee  #smcr   ...
26     31989              chick gets fucked hottest naked lady 
27     31990  happy bday lucy✨✨🎈 xoxo #love #beautifu...
28     31991   haroldfriday have a weekend filled with sunbe...
29     31992  @user @user tried that! but nothing - will try...
...      ...                                                ...
17167  49130  people do anything for fucking attention nowad...
17168  49131  creative bubble got burst 😢 looking forward...
17169  49132  tomorrow is gonna be a big day! we are going t...
17170  49133  i am thankful for baby giggles. #thankful #pos...
17171  49134  #model   i love u take with u all the time in ...
17172  49135  in life u will grow to learn some pple will wo...
17173  49136  💙i was the storm,you were the rain. togethe...
17174  49137  lovelgq -  broken ep via   #rnb #love #heabrok...
17175  49138  spread love not hate❤️💛💚💙💜 #pr...
17176  49139     @user @user are the most racist pay ever!!!!! 
17177  49140  i am thankful for children. #thankful #positiv...
17178  49141  liverpool ❤️🇬🇧 #walk #liverpool #sta...
17179  49142  #bakersfield   rooster simulation: i want to c...
17180  49143  por do sol 󾀋❤️#instagood #beautiful   #...
17181  49144  @user hell yeah what a great surprise for your...
17182  49145  when ur the joke ur defensive towards everythi...
17183  49146  #enjoying the #evening #sun in my #bedroom ✨...
17184  49147  tonight on @user from 9pm gmt  you can here a ...
17185  49148  today is a good day for excercise #imready #so...
17186  49149  good night with a tea and music ☕️👌🙌...
17187  49150  loving life🇺🇸☀️🏊  #createyourfutu...
17188  49151  black professor demonizes, proposes nazi style...
17189  49152  learn how to think positive.  #positive   #ins...
17190  49153  we love the pretty, happy and fresh you! #teen...
17191  49154  2_damn_tuff-ruff_muff__techno_city-(ng005)-web...
17192  49155  thought factory: left-right polarisation! #tru...
17193  49156  feeling like a mermaid 😘 #hairflip #neverre...
17194  49157  #hillary #campaigned today in #ohio((omg)) &am...
17195  49158  happy, at work conference: right mindset leads...
17196  49159  my   song "so glad" free download!  #shoegaze ...

[17197 rows x 2 columns]

In [54]:
X4=df1['tweet']
X4.shape

(17197,)

In [55]:
#from sklearn.feature_extraction.text import CountVectorizer
#vect=CountVectorizer()
X_test9=vect.transform(X4)
X_test9.shape

(17197, 34472)

In [36]:
y8=DT.predict(X_test9)

In [57]:
y8

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [58]:
df1['label']=y8

In [59]:
new_file=df1.to_csv('Twitter.csv')
new_file

In [60]:
read_file=pd.read_csv('Twitter.csv')

In [61]:
read_file

Unnamed: 0     id                                              tweet  \
0               0  31963  #studiolife #aislife #requires #passion #dedic...   
1               1  31964   @user #white #supremacists want everyone to s...   
2               2  31965  safe ways to heal your #acne!!    #altwaystohe...   
3               3  31966  is the hp and the cursed child book up for res...   
4               4  31967    3rd #bihday to my amazing, hilarious #nephew...   
5               5  31968                        choose to be   :) #momtips    
6               6  31969  something inside me dies 💦💿✨  eyes nes...   
7               7  31970  #finished#tattoo#inked#ink#loveit❤️ #❤ï¸...   
8               8  31971   @user @user @user i will never understand why...   
9               9  31972  #delicious   #food #lovelife #capetown mannaep...   
10             10  31973  1000dayswasted - narcosis infinite ep.. make m...   
11             11  31974  one of the world's greatest spoing events   #l...   
12             12  31975  half way through the website now and #allgoing...   
13             13  31976  good food, good life , #enjoy and   🙌🍕ðŸ...   
14             14  31977  i'll stand behind this #guncontrolplease   #se...   
15             15  31978  i ate,i ate and i ate...😀😊   #jamaisasth...   
16             16  31979   @user got my @user limited edition rain or sh...   
17             17  31980  &amp; #love &amp; #hugs &amp; #kisses too! how...   
18             18  31981  👭🌞💖 #girls   #sun #fave @ london, uni...   
19             19  31982  thought factory: bbc neutrality on right wing ...   
20             20  31983  hey guys tommorow is the last day of my exams ...   
21             21  31984   @user @user  @user  #levyrroni #recuerdos mem...   
22             22  31985  my mind is like 🎉💃🏽🏀 but my body l...   
23             23  31986  never been this down on myself in my entire li...   
24             24  31987  check  twitterww - trends: "trending worldwide...   
25             25  31988  i thought i saw a mermaid!!! #ceegee  #smcr   ...   
26             26  31989              chick gets fucked hottest naked lady    
27             27  31990  happy bday lucy✨✨🎈 xoxo #love #beautifu...   
28             28  31991   haroldfriday have a weekend filled with sunbe...   
29             29  31992  @user @user tried that! but nothing - will try...   
...           ...    ...                                                ...   
17167       17167  49130  people do anything for fucking attention nowad...   
17168       17168  49131  creative bubble got burst 😢 looking forward...   
17169       17169  49132  tomorrow is gonna be a big day! we are going t...   
17170       17170  49133  i am thankful for baby giggles. #thankful #pos...   
17171       17171  49134  #model   i love u take with u all the time in ...   
17172       17172  49135  in life u will grow to learn some pple will wo...   
17173       17173  49136  💙i was the storm,you were the rain. togethe...   
17174       17174  49137  lovelgq -  broken ep via   #rnb #love #heabrok...   
17175       17175  49138  spread love not hate❤️💛💚💙💜 #pr...   
17176       17176  49139     @user @user are the most racist pay ever!!!!!    
17177       17177  49140  i am thankful for children. #thankful #positiv...   
17178       17178  49141  liverpool ❤️🇬🇧 #walk #liverpool #sta...   
17179       17179  49142  #bakersfield   rooster simulation: i want to c...   
17180       17180  49143  por do sol 󾀋❤️#instagood #beautiful   #...   
17181       17181  49144  @user hell yeah what a great surprise for your...   
17182       17182  49145  when ur the joke ur defensive towards everythi...   
17183       17183  49146  #enjoying the #evening #sun in my #bedroom ✨...   
17184       17184  49147  tonight on @user from 9pm gmt  you can here a ...   
17185       17185  49148  today is a good day for excerci

In [62]:
import os
os.getcwd()

'C:\\Users\\hp'